### ISSUE TITLE
Refactor all patterns that use container iterator in the wrong way

### ISSUE THREAD

**Issue by vgene** [PrincetonUniversity/cpf#26]
## Problem
In [Speculation/Classify.cpp](https://github.com/PrincetonUniversity/cpf/blob/6acbbe07a9a9fa3870397b7d5898cd2fe508ad2c/liberty/lib/Speculation/Classify.cpp#L1252), we are using iterator loop of stl containers and then remove elements based on some condition. This is wrong! Removing an element invalidate the iterator and reusing that iterator will lead to segfault.

Instead of pattern like:
```cpp
for (auto i : cheapPrivAUs) {
   if (LoopAA::containsExpensiveRemeds(i.second))
     cheapPrivAUs.erase(i.first);
 }
```

We need to use iterator more explicitly to avoid the problem ([source](https://www.techiedelight.com/remove-elements-vector-inside-loop-cpp/)):
```cpp
    auto it = v.begin();
    while (it != v.end())
    {
        // remove odd numbers
        if (*it & 1) {
            // erase() invalidates the iterator, use returned iterator
            it = v.erase(it);
        }
        // Notice that iterator is incremented only on the else part (why?)
        else {
            ++it;
        }
    }
```

## TODOs
- [ ] Find all patterns like this
- [ ] Refactor the code with

**Comment by vgene** [comment]
@gchan510 Please close this today.

**Comment by gchan510** [comment]
All cases are fixed except for the ones in `CodeGen/Postprocess.cpp:606,628,809`

ETA: tomorrow

**Comment by vgene** [comment]
@gchan510

**Comment by VictorYing** [comment]
Hi, I found this repo and was came to see what recent development looks like after reading the Perspective and SCAF papers. Seems like you're doing cool work. Upon reading this issue, I thought I'd point out that there is a standard C++ idiom to remove items from a container without resorting to directly manipulating iterators: [the erase-remove idiom](https://en.m.wikipedia.org/wiki/Erase%E2%80%93remove_idiom). The remove-erase idiom is guaranteed to execute the predicate code (often a lambda) exactly once per element of the container, and this idiom is often more efficient in addition to less error-prone than direct use of iterators.

llvm has a generic utility `llvm::erase_if` in llvm/ADT/STLExtras.h that makes the remove-erase idiom even easier.

**Comment by vgene** [comment]
@VictorYing Thank you for the comment! Please also let us know if you are interested in a tutorial of the current system and the recent development effort.

**Comment by VictorYing** [comment]
For sure, maybe after I'm finished with the MICRO deadline, we can chat?

**Comment by gchan510** [comment]
Cases mentioned in https://github.com/PrincetonUniversity/cpf/issues/26#issuecomment-789503397 are ok. Every time the iterator is invalidated the outer loop starts iterating again from the beginning. It's not the cleanest way but it works so I'm closing this issue. If it becomes a performance bottleneck in the future we can reopen it.
