### ISSUE TITLE
SVF Seg Fault

### ISSUE THREAD

**Issue by SusanTan** [PrincetonUniversity/cpf#7]
**Benchmark**: 508.namd
**How to reproduce**: with inline enabled, check benchmark.collaborative-pipeline.dump
**Error Message**:
![image](https://user-images.githubusercontent.com/31673326/87154742-c03fc680-c287-11ea-8f87-3e2e939f9b53.png)

**Comment by vgene** [comment]
Close this unless proved otherwise
